#!/usr/bin/env python3
"""Operator-facing entry point for the Elastispec Auditor."""

from __future__ import annotations

import argparse
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import uuid
from pathlib import Path
from typing import Sequence


SCRIPT_DIR = Path(__file__).resolve().parent


def _existing_file(raw_path: str, label: str) -> Path:
    path = Path(raw_path).expanduser()
    if not path.is_file():
        raise SystemExit(f"{label} file not found: {path}")
    return path.resolve()


def _run_stage(name: str, command: Sequence[str]) -> None:
    completed = subprocess.run(command, text=True, capture_output=True)
    if completed.returncode == 0:
        return
    details = completed.stderr.strip() or completed.stdout.strip()
    message = f"{name} failed"
    if details:
        message += f":\n{details}"
    raise SystemExit(message)


def _wait_for_batfish(host: str, timeout_seconds: float) -> None:
    if timeout_seconds <= 0:
        return
    deadline = time.monotonic() + timeout_seconds
    print(f"[WAIT] Batfish coordinator at {host}:9996")
    while True:
        try:
            with socket.create_connection((host, 9996), timeout=2):
                print(f"[READY] Batfish coordinator at {host}:9996")
                return
        except OSError as exc:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise SystemExit(
                    f"Batfish did not become available at {host}:9996 within "
                    f"{timeout_seconds:g} seconds"
                ) from exc
            time.sleep(min(1.0, remaining))


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Audit a firewall configuration against an Elastispec specification "
            "and write one compliance report."
        )
    )
    parser.add_argument("--config", required=True, help="Complete Cisco firewall configuration")
    parser.add_argument(
        "--inventory",
        required=True,
        help="Elastispec server inventory JSON",
    )
    parser.add_argument(
        "--spec",
        required=True,
        help="Elastispec specification generated by the Translator",
    )
    parser.add_argument("--output", required=True, help="Output compliance report")
    parser.add_argument("--title", default="", help="Optional report title")
    parser.add_argument(
        "--batfish_data_dir",
        default="~/batfish-data",
        help="Host directory mounted at /data in the custom Batfish container",
    )
    parser.add_argument(
        "--batfish_host",
        default="localhost",
        help="Batfish coordinator hostname (default: localhost)",
    )
    parser.add_argument(
        "--batfish_startup_timeout",
        type=float,
        default=0,
        help="Seconds to wait for Batfish to start; 0 disables waiting",
    )
    args = parser.parse_args()

    config_path = _existing_file(args.config, "Firewall configuration")
    inventory_path = _existing_file(args.inventory, "Inventory")
    spec_path = _existing_file(args.spec, "Specification")
    batfish_data_dir = Path(args.batfish_data_dir).expanduser().resolve()
    if not batfish_data_dir.is_dir():
        raise SystemExit(f"Batfish data directory not found: {batfish_data_dir}")
    batfish_host = str(args.batfish_host).strip()
    if not batfish_host:
        raise SystemExit("--batfish_host cannot be empty")
    if args.batfish_startup_timeout < 0:
        raise SystemExit("--batfish_startup_timeout cannot be negative")

    output_path = Path(args.output).expanduser().resolve()
    if output_path.suffix.lower() != ".html":
        raise SystemExit(f"--output must be an .html file: {output_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    _wait_for_batfish(batfish_host, args.batfish_startup_timeout)

    run_id = uuid.uuid4().hex[:10]
    with tempfile.TemporaryDirectory(prefix="elastispec-auditor-") as tmp_raw:
        tmp_dir = Path(tmp_raw)
        snapshot_dir = tmp_dir / "snapshot"
        intermediate_dir = tmp_dir / "intermediate"
        rendered_html = tmp_dir / "report.html"
        rendered_txt = tmp_dir / "report.txt"

        build_command = [
            sys.executable,
            str(SCRIPT_DIR / "build_snapshot.py"),
            "--config",
            str(config_path),
            "--inventory",
            str(inventory_path),
            "--output_dir",
            str(snapshot_dir),
        ]
        _run_stage("Snapshot preparation", build_command)

        bdd_debug_path = batfish_data_dir / "debug_bdd_reachability.json"
        audit_command = [
            sys.executable,
            str(SCRIPT_DIR / "run_audit.py"),
            str(snapshot_dir),
            str(spec_path),
            "--output_dir",
            str(intermediate_dir),
            "--network",
            f"elastispec_audit_net_{run_id}",
            "--snapshot",
            f"elastispec_audit_ss_{run_id}",
            "--batfish_host",
            batfish_host,
        ]
        audit_command.extend(
            [
                "--bdd_debug_json_path",
                str(bdd_debug_path),
            ]
        )
        try:
            _run_stage("Firewall audit", audit_command)
        finally:
            bdd_debug_path.unlink(missing_ok=True)

        summaries = sorted(intermediate_dir.glob("audit_*.summary.txt"))
        if len(summaries) != 1:
            raise SystemExit(
                "Firewall audit did not produce exactly one intermediate summary"
            )

        render_command = [
            sys.executable,
            str(SCRIPT_DIR / "render_tree.py"),
            "--fsl",
            str(spec_path),
            "--summary",
            str(summaries[0]),
            "--out_html",
            str(rendered_html),
            "--out_txt",
            str(rendered_txt),
            "--title",
            str(args.title or f"Elastispec audit: {config_path.stem}"),
        ]
        _run_stage("Compliance report rendering", render_command)

        shutil.copy2(rendered_html, output_path)

    print(f"[DONE] wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
